[site]
url=https://www.bossku.eu.org
name = HOMESERVER
#the background of website
background = img/backg.jpg
#meta robots
robots=noindex,nofollow 
#meta img
og:image=img/netwrks.png 

[Menu]
item[] = "Home|https://www.bossku.eu.org/"
item[] = "Services|services.php"
item[] = "About|about.php"
item[] = "text 3|httpurl3"
item[] = "text 4|httpurl4"
#add more items

[page]
#meta title for index.php
index.title = DASHBOARD
#meta description for index.php
index.desc = Ini adalah homeserver kedua saya, bermula ketika saya memerlukan sistem muat turun harian data cadangan dari beberapa laman web yang saya uruskan.
#meta title for about.php
about.title = ABOUT
#meta description for about.php
about.desc = This is my second homemeserver, it started when i needed a system to download daily backup data from several websites I manage.
#meta title for services.php
services.title = THE TITLE
#meta description for services.php
services.desc = The description.
#add more meta according to php slug

[AdGuard]
#can replace with custom domain, do not add / at the end of url
url=http://192.168.0.3:3000
#AdGuard username
user= 
#AdGuard password
pass=

[Immich]
#can replace with custom domain, do not add / at the end of url
url= http://192.168.0.3:2283
#The API KEY is available in the dashboard
key= API-KEY
